export {default as endPage} from './endPage';
export {default as datetime} from './datetime';
export {default as parseError} from './parseError';
export {changeITD, parseDate, ChangeDTI, formatDate} from './changeTime';
export {validateEmail} from './validate';
export {setValue, setValueLogin, setObjValue} from './setValue';
export {default as initObject} from './initObject';
export {default as renderField} from './renderField';
export {default as renderInfo} from './renderInfo';
export {preprocess, preprocessPost} from './preprocess';
export {default as checkRequire} from './checkRequire';
export {default as makeQuery} from './makeQuery';
export let defaultimg = '../images/defautl.jpg';
export {default as numeral} from './numeral';
