export const ME_LOAD = "ME_LOAD";
export const ME_LOAD_SUCCESS = "ME_LOAD_SUCCESS";
export const ME_LOAD_FAIL = "ME_LOAD_FAIL";

export const LOGIN_LOAD = "LOGIN_LOAD";
export const LOGIN_LOAD_SUCCESS = "LOGIN_LOAD_SUCCESS";
export const LOGIN_LOAD_FAIL = "LOGIN_LOAD_FAIL";

export const REGISTER_LOAD = "REGISTER_LOAD";
export const REGISTER_LOAD_SUCCESS = "REGISTER_LOAD_SUCCESS";
export const REGISTER_LOAD_FAIL = "REGISTER_LOAD_FAIL";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const LOGOUT_LOAD = "LOGOUT_LOAD";
export const LOGOUT_LOAD_SUCCESS = "LOGOUT_LOAD_SUCCESS";
export const LOGOUT_LOAD_FAIL = "LOGOUT_LOAD_FAIL";

export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL";
export const LIST_IMAGE = "LIST_IMAGE";
export const LIST_IMAGE_SUCCESS = "LIST_IMAGE_SUCCESS";
export const LIST_IMAGE_FAIL = "LIST_IMAGE_FAIL";
export const SELECT_IMAGE = "SELECT_IMAGE";
export const SELECT_IMAGE_SUCCESS = "SELECT_IMAGE_SUCCESS";
export const SELECT_IMAGE_FAIL = "SELECT_IMAGE_FAIL";

// KHACH HANG
export const KH_LIST_LOAD = "KH_LIST_LOAD";
export const KH_LIST_LOAD_SUCCESS = "KH_LIST_LOAD_SUCCESS";
export const KH_LIST_LOAD_FAIL = "KH_LIST_LOAD_FAIL";

export const KH_ONE_LOAD = "KH_ONE_LOAD";
export const KH_ONE_LOAD_SUCCESS = "KH_ONE_LOAD_SUCCESS";
export const KH_ONE_LOAD_FAIL = "KH_ONE_LOAD_FAIL";

export const KH_POST = "KH_POST";
export const KH_POST_SUCCESS = "KH_POST_SUCCESS";
export const KH_POST_FAIL = "KH_POST_FAIL";

export const KH_PUT = "KH_PUT";
export const KH_PUT_SUCCESS = "KH_PUT_SUCCESS";
export const KH_PUT_FAIL = "KH_PUT_FAIL";

export const KH_DELETE = "KH_DELETE";
export const KH_DELETE_SUCCESS = "KH_DELETE_SUCCESS";
export const KH_DELETE_FAIL = "KH_DELETE_FAIL";

export const KH_GET = "KH_GET";
export const KH_GET_SUCCESS = "KH_GET_SUCCESS";
export const KH_GET_FAIL = "KH_GET_FAIL";

export const KH_RESET = "KH_RESET";

// NHA CUNG CAP
export const NCC_LIST_LOAD = "NCC_LIST_LOAD";
export const NCC_LIST_LOAD_SUCCESS = "NCC_LIST_LOAD_SUCCESS";
export const NCC_LIST_LOAD_FAIL = "NCC_LIST_LOAD_FAIL";

export const NCC_ONE_LOAD = "NCC_ONE_LOAD";
export const NCC_ONE_LOAD_SUCCESS = "NCC_ONE_LOAD_SUCCESS";
export const NCC_ONE_LOAD_FAIL = "NCC_ONE_LOAD_FAIL";

export const NCC_POST = "NCC_POST";
export const NCC_POST_SUCCESS = "NCC_POST_SUCCESS";
export const NCC_POST_FAIL = "NCC_POST_FAIL";

export const NCC_PUT = "NCC_PUT";
export const NCC_PUT_SUCCESS = "NCC_PUT_SUCCESS";
export const NCC_PUT_FAIL = "NCC_PUT_FAIL";

export const NCC_DELETE = "NCC_DELETE";
export const NCC_DELETE_SUCCESS = "NCC_DELETE_SUCCESS";
export const NCC_DELETE_FAIL = "NCC_DELETE_FAIL";

export const NCC_GET = "NCC_GET";
export const NCC_GET_SUCCESS = "NCC_GET_SUCCESS";
export const NCC_GET_FAIL = "NCC_GET_FAIL";

export const NCC_RESET = "NCC_RESET";

// NHAN VIEN
export const NV_LIST_LOAD = "NV_LIST_LOAD";
export const NV_LIST_LOAD_SUCCESS = "NV_LIST_LOAD_SUCCESS";
export const NV_LIST_LOAD_FAIL = "NV_LIST_LOAD_FAIL";

export const NV_ONE_LOAD = "NV_ONE_LOAD";
export const NV_ONE_LOAD_SUCCESS = "NV_ONE_LOAD_SUCCESS";
export const NV_ONE_LOAD_FAIL = "NV_ONE_LOAD_FAIL";

export const NV_POST = "NV_POST";
export const NV_POST_SUCCESS = "NV_POST_SUCCESS";
export const NV_POST_FAIL = "NV_POST_FAIL";

export const NV_PUT = "NV_PUT";
export const NV_PUT_SUCCESS = "NV_PUT_SUCCESS";
export const NV_PUT_FAIL = "NV_PUT_FAIL";

export const NV_DELETE = "NV_DELETE";
export const NV_DELETE_SUCCESS = "NV_DELETE_SUCCESS";
export const NV_DELETE_FAIL = "NV_DELETE_FAIL";

export const NV_GET = "NV_GET";
export const NV_GET_SUCCESS = "NV_GET_SUCCESS";
export const NV_GET_FAIL = "NV_GET_FAIL";

export const NV_RESET = "NV_RESET";

// KHO
export const KHO_LIST_LOAD = "KHO_LIST_LOAD";
export const KHO_LIST_LOAD_SUCCESS = "KHO_LIST_LOAD_SUCCESS";
export const KHO_LIST_LOAD_FAIL = "KHO_LIST_LOAD_FAIL";

export const KHO_ONE_LOAD = "KHO_ONE_LOAD";
export const KHO_ONE_LOAD_SUCCESS = "KHO_ONE_LOAD_SUCCESS";
export const KHO_ONE_LOAD_FAIL = "KHO_ONE_LOAD_FAIL";

export const KHO_POST = "KHO_POST";
export const KHO_POST_SUCCESS = "KHO_POST_SUCCESS";
export const KHO_POST_FAIL = "KHO_POST_FAIL";

export const KHO_PUT = "KHO_PUT";
export const KHO_PUT_SUCCESS = "KHO_PUT_SUCCESS";
export const KHO_PUT_FAIL = "KHO_PUT_FAIL";

export const KHO_DELETE = "KHO_DELETE";
export const KHO_DELETE_SUCCESS = "KHO_DELETE_SUCCESS";
export const KHO_DELETE_FAIL = "KHO_DELETE_FAIL";

export const KHO_GET = "KHO_GET";
export const KHO_GET_SUCCESS = "KHO_GET_SUCCESS";
export const KHO_GET_FAIL = "KHO_GET_FAIL";

export const KHO_RESET = "KHO_RESET";

// LOAI VAI
export const LV_LIST_LOAD = "LV_LIST_LOAD";
export const LV_LIST_LOAD_SUCCESS = "LV_LIST_LOAD_SUCCESS";
export const LV_LIST_LOAD_FAIL = "LV_LIST_LOAD_FAIL";

export const LV_ONE_LOAD = "LV_ONE_LOAD";
export const LV_ONE_LOAD_SUCCESS = "LV_ONE_LOAD_SUCCESS";
export const LV_ONE_LOAD_FAIL = "LV_ONE_LOAD_FAIL";

export const LV_POST = "LV_POST";
export const LV_POST_SUCCESS = "LV_POST_SUCCESS";
export const LV_POST_FAIL = "LV_POST_FAIL";

export const LV_PUT = "LV_PUT";
export const LV_PUT_SUCCESS = "LV_PUT_SUCCESS";
export const LV_PUT_FAIL = "LV_PUT_FAIL";

export const LV_DELETE = "LV_DELETE";
export const LV_DELETE_SUCCESS = "LV_DELETE_SUCCESS";
export const LV_DELETE_FAIL = "LV_DELETE_FAIL";

export const LV_GET = "LV_GET";
export const LV_GET_SUCCESS = "LV_GET_SUCCESS";
export const LV_GET_FAIL = "LV_GET_FAIL";

export const LV_RESET = "LV_RESET";

// LO HANG
export const LH_LIST_LOAD = "LH_LIST_LOAD";
export const LH_LIST_LOAD_SUCCESS = "LH_LIST_LOAD_SUCCESS";
export const LH_LIST_LOAD_FAIL = "LH_LIST_LOAD_FAIL";

export const LH_ONE_LOAD = "LH_ONE_LOAD";
export const LH_ONE_LOAD_SUCCESS = "LH_ONE_LOAD_SUCCESS";
export const LH_ONE_LOAD_FAIL = "LH_ONE_LOAD_FAIL";

export const LH_POST = "LH_POST";
export const LH_POST_SUCCESS = "LH_POST_SUCCESS";
export const LH_POST_FAIL = "LH_POST_FAIL";

export const LH_PUT = "LH_PUT";
export const LH_PUT_SUCCESS = "LH_PUT_SUCCESS";
export const LH_PUT_FAIL = "LH_PUT_FAIL";

export const LH_DELETE = "LH_DELETE";
export const LH_DELETE_SUCCESS = "LH_DELETE_SUCCESS";
export const LH_DELETE_FAIL = "LH_DELETE_FAIL";

export const LH_RESET = "LH_RESET";

// PHIEU DAT HANG CHO NHA CUNG CAP
export const PDH_LIST_LOAD = "PDH_LIST_LOAD";
export const PDH_LIST_LOAD_SUCCESS = "PDH_LIST_LOAD_SUCCESS";
export const PDH_LIST_LOAD_FAIL = "PDH_LIST_LOAD_FAIL";

export const PDH_ONE_LOAD = "PDH_ONE_LOAD";
export const PDH_ONE_LOAD_SUCCESS = "PDH_ONE_LOAD_SUCCESS";
export const PDH_ONE_LOAD_FAIL = "PDH_ONE_LOAD_FAIL";

export const PDH_POST = "PDH_POST";
export const PDH_POST_SUCCESS = "PDH_POST_SUCCESS";
export const PDH_POST_FAIL = "PDH_POST_FAIL";

export const PDH_PUT = "PDH_PUT";
export const PDH_PUT_SUCCESS = "PDH_PUT_SUCCESS";
export const PDH_PUT_FAIL = "PDH_PUT_FAIL";

export const PDH_DELETE = "PDH_DELETE";
export const PDH_DELETE_SUCCESS = "PDH_DELETE_SUCCESS";
export const PDH_DELETE_FAIL = "PDH_DELETE_FAIL";

export const PDH_CTDH = "PDH_CTDH";
export const PDH_CTDH_SUCCESS = "PDH_CTDH_SUCCESS";
export const PDH_CTDH_FAIL = "PDH_CTDH_FAIL";

export const PDH_GET = "PDH_GET";
export const PDH_GET_SUCCESS = "PDH_GET_SUCCESS";
export const PDH_GET_FAIL = "PDH_GET_FAIL";

export const PDH_RESET = "PDH_RESET";

// PHIEU NHAP HANG TU NHA CUNG CAP
export const PNH_LIST_LOAD = "PNH_LIST_LOAD";
export const PNH_LIST_LOAD_SUCCESS = "PNH_LIST_LOAD_SUCCESS";
export const PNH_LIST_LOAD_FAIL = "PNH_LIST_LOAD_FAIL";

export const PNH_ONE_LOAD = "PNH_ONE_LOAD";
export const PNH_ONE_LOAD_SUCCESS = "PNH_ONE_LOAD_SUCCESS";
export const PNH_ONE_LOAD_FAIL = "PNH_ONE_LOAD_FAIL";

export const PNH_POST = "PNH_POST";
export const PNH_POST_SUCCESS = "PNH_POST_SUCCESS";
export const PNH_POST_FAIL = "PNH_POST_FAIL";

export const PNH_PUT = "PNH_PUT";
export const PNH_PUT_SUCCESS = "PNH_PUT_SUCCESS";
export const PNH_PUT_FAIL = "PNH_PUT_FAIL";

export const PNH_DELETE = "PNH_DELETE";
export const PNH_DELETE_SUCCESS = "PNH_DELETE_SUCCESS";
export const PNH_DELETE_FAIL = "PNH_DELETE_FAIL";

export const PNH_CTK = "PNH_CTK";
export const PNH_CTK_SUCCESS = "PNH_CTK_SUCCESS";
export const PNH_CTK_FAIL = "PNH_CTK_FAIL";

export const PNH_GET = "PNH_GET";
export const PNH_GET_SUCCESS = "PNH_GET_SUCCESS";
export const PNH_GET_FAIL = "PNH_GET_FAIL";

export const PNH_RESET = "PNH_RESET";

// PHIEU MUA HANG CHO KHACH HANG
export const PMH_LIST_LOAD = "PMH_LIST_LOAD";
export const PMH_LIST_LOAD_SUCCESS = "PMH_LIST_LOAD_SUCCESS";
export const PMH_LIST_LOAD_FAIL = "PMH_LIST_LOAD_FAIL";

export const PMH_ONE_LOAD = "PMH_ONE_LOAD";
export const PMH_ONE_LOAD_SUCCESS = "PMH_ONE_LOAD_SUCCESS";
export const PMH_ONE_LOAD_FAIL = "PMH_ONE_LOAD_FAIL";

export const PMH_POST = "PMH_POST";
export const PMH_POST_SUCCESS = "PMH_POST_SUCCESS";
export const PMH_POST_FAIL = "PMH_POST_FAIL";

export const PMH_PUT = "PMH_PUT";
export const PMH_PUT_SUCCESS = "PMH_PUT_SUCCESS";
export const PMH_PUT_FAIL = "PMH_PUT_FAIL";

export const PMH_DELETE = "PMH_DELETE";
export const PMH_DELETE_SUCCESS = "PMH_DELETE_SUCCESS";
export const PMH_DELETE_FAIL = "PMH_DELETE_FAIL";

export const PMH_CTDH = "PMH_CTDH";
export const PMH_CTDH_SUCCESS = "PMH_CTDH_SUCCESS";
export const PMH_CTDH_FAIL = "PMH_CTDH_FAIL";

export const PMH_GET = "PMH_GET";
export const PMH_GET_SUCCESS = "PMH_GET_SUCCESS";
export const PMH_GET_FAIL = "PMH_GET_FAIL";

export const PMH_RESET = "PMH_RESET";

// PHIEU XUAT HANG CHO KHACH HANG
export const PXH_LIST_LOAD = "PXH_LIST_LOAD";
export const PXH_LIST_LOAD_SUCCESS = "PXH_LIST_LOAD_SUCCESS";
export const PXH_LIST_LOAD_FAIL = "PXH_LIST_LOAD_FAIL";

export const PXH_ONE_LOAD = "PXH_ONE_LOAD";
export const PXH_ONE_LOAD_SUCCESS = "PXH_ONE_LOAD_SUCCESS";
export const PXH_ONE_LOAD_FAIL = "PXH_ONE_LOAD_FAIL";

export const PXH_POST = "PXH_POST";
export const PXH_POST_SUCCESS = "PXH_POST_SUCCESS";
export const PXH_POST_FAIL = "PXH_POST_FAIL";

export const PXH_PUT = "PXH_PUT";
export const PXH_PUT_SUCCESS = "PXH_PUT_SUCCESS";
export const PXH_PUT_FAIL = "PXH_PUT_FAIL";

export const PXH_DELETE = "PXH_DELETE";
export const PXH_DELETE_SUCCESS = "PXH_DELETE_SUCCESS";
export const PXH_DELETE_FAIL = "PXH_DELETE_FAIL";

export const PXH_CTK = "PXH_CTK";
export const PXH_CTK_SUCCESS = "PXH_CTK_SUCCESS";
export const PXH_CTK_FAIL = "PXH_CTK_FAIL";

export const PXH_GET = "PXH_GET";
export const PXH_GET_SUCCESS = "PXH_GET_SUCCESS";
export const PXH_GET_FAIL = "PXH_GET_FAIL";

export const PXH_RESET = "PXH_RESET";

// HOA DON KHACH HANG
export const HDKH_LIST_LOAD = "HDKH_LIST_LOAD";
export const HDKH_LIST_LOAD_SUCCESS = "HDKH_LIST_LOAD_SUCCESS";
export const HDKH_LIST_LOAD_FAIL = "HDKH_LIST_LOAD_FAIL";

export const HDKH_ONE_LOAD = "HDKH_ONE_LOAD";
export const HDKH_ONE_LOAD_SUCCESS = "HDKH_ONE_LOAD_SUCCESS";
export const HDKH_ONE_LOAD_FAIL = "HDKH_ONE_LOAD_FAIL";

export const HDKH_POST = "HDKH_POST";
export const HDKH_POST_SUCCESS = "HDKH_POST_SUCCESS";
export const HDKH_POST_FAIL = "HDKH_POST_FAIL";

export const HDKH_PUT = "HDKH_PUT";
export const HDKH_PUT_SUCCESS = "HDKH_PUT_SUCCESS";
export const HDKH_PUT_FAIL = "HDKH_PUT_FAIL";

export const HDKH_DELETE = "HDKH_DELETE";
export const HDKH_DELETE_SUCCESS = "HDKH_DELETE_SUCCESS";
export const HDKH_DELETE_FAIL = "HDKH_DELETE_FAIL";

export const HDKH_RESET = "HDKH_RESET";

// HOA DON NHA CUNG CAP
export const HDNCC_LIST_LOAD = "HDNCC_LIST_LOAD";
export const HDNCC_LIST_LOAD_SUCCESS = "HDNCC_LIST_LOAD_SUCCESS";
export const HDNCC_LIST_LOAD_FAIL = "HDNCC_LIST_LOAD_FAIL";

export const HDNCC_ONE_LOAD = "HDNCC_ONE_LOAD";
export const HDNCC_ONE_LOAD_SUCCESS = "HDNCC_ONE_LOAD_SUCCESS";
export const HDNCC_ONE_LOAD_FAIL = "HDNCC_ONE_LOAD_FAIL";

export const HDNCC_POST = "HDNCC_POST";
export const HDNCC_POST_SUCCESS = "HDNCC_POST_SUCCESS";
export const HDNCC_POST_FAIL = "HDNCC_POST_FAIL";

export const HDNCC_PUT = "HDNCC_PUT";
export const HDNCC_PUT_SUCCESS = "HDNCC_PUT_SUCCESS";
export const HDNCC_PUT_FAIL = "HDNCC_PUT_FAIL";

export const HDNCC_DELETE = "HDNCC_DELETE";
export const HDNCC_DELETE_SUCCESS = "HDNCC_DELETE_SUCCESS";
export const HDNCC_DELETE_FAIL = "HDNCC_DELETE_FAIL";

export const HDNCC_RESET = "HDNCC_RESET";

// THANH TOAN KHACH HANG
export const TTKH_LIST_LOAD = "TTKH_LIST_LOAD";
export const TTKH_LIST_LOAD_SUCCESS = "TTKH_LIST_LOAD_SUCCESS";
export const TTKH_LIST_LOAD_FAIL = "TTKH_LIST_LOAD_FAIL";

export const TTKH_ONE_LOAD = "TTKH_ONE_LOAD";
export const TTKH_ONE_LOAD_SUCCESS = "TTKH_ONE_LOAD_SUCCESS";
export const TTKH_ONE_LOAD_FAIL = "TTKH_ONE_LOAD_FAIL";

export const TTKH_POST = "TTKH_POST";
export const TTKH_POST_SUCCESS = "TTKH_POST_SUCCESS";
export const TTKH_POST_FAIL = "TTKH_POST_FAIL";

export const TTKH_PUT = "TTKH_PUT";
export const TTKH_PUT_SUCCESS = "TTKH_PUT_SUCCESS";
export const TTKH_PUT_FAIL = "TTKH_PUT_FAIL";

export const TTKH_DELETE = "TTKH_DELETE";
export const TTKH_DELETE_SUCCESS = "TTKH_DELETE_SUCCESS";
export const TTKH_DELETE_FAIL = "TTKH_DELETE_FAIL";

export const TTKH_RESET = "TTKH_RESET";

// THANH TOAN NHA CUNG CAP
export const TTNCC_LIST_LOAD = "TTNCC_LIST_LOAD";
export const TTNCC_LIST_LOAD_SUCCESS = "TTNCC_LIST_LOAD_SUCCESS";
export const TTNCC_LIST_LOAD_FAIL = "TTNCC_LIST_LOAD_FAIL";

export const TTNCC_ONE_LOAD = "TTNCC_ONE_LOAD";
export const TTNCC_ONE_LOAD_SUCCESS = "TTNCC_ONE_LOAD_SUCCESS";
export const TTNCC_ONE_LOAD_FAIL = "TTNCC_ONE_LOAD_FAIL";

export const TTNCC_POST = "TTNCC_POST";
export const TTNCC_POST_SUCCESS = "TTNCC_POST_SUCCESS";
export const TTNCC_POST_FAIL = "TTNCC_POST_FAIL";

export const TTNCC_PUT = "TTNCC_PUT";
export const TTNCC_PUT_SUCCESS = "TTNCC_PUT_SUCCESS";
export const TTNCC_PUT_FAIL = "TTNCC_PUT_FAIL";

export const TTNCC_DELETE = "TTNCC_DELETE";
export const TTNCC_DELETE_SUCCESS = "TTNCC_DELETE_SUCCESS";
export const TTNCC_DELETE_FAIL = "TTNCC_DELETE_FAIL";

export const TTNCC_RESET = "TTNCC_RESET";
// CONG NO KHACH HANG
export const CNKH_LIST_LOAD = "CNKH_LIST_LOAD";
export const CNKH_LIST_LOAD_SUCCESS = "CNKH_LIST_LOAD_SUCCESS";
export const CNKH_LIST_LOAD_FAIL = "CNKH_LIST_LOAD_FAIL";

export const CNKH_ONE_LOAD = "CNKH_ONE_LOAD";
export const CNKH_ONE_LOAD_SUCCESS = "CNKH_ONE_LOAD_SUCCESS";
export const CNKH_ONE_LOAD_FAIL = "CNKH_ONE_LOAD_FAIL";

export const CNKH_POST = "CNKH_POST";
export const CNKH_POST_SUCCESS = "CNKH_POST_SUCCESS";
export const CNKH_POST_FAIL = "CNKH_POST_FAIL";

export const CNKH_PUT = "CNKH_PUT";
export const CNKH_PUT_SUCCESS = "CNKH_PUT_SUCCESS";
export const CNKH_PUT_FAIL = "CNKH_PUT_FAIL";

export const CNKH_DELETE = "CNKH_DELETE";
export const CNKH_DELETE_SUCCESS = "CNKH_DELETE_SUCCESS";
export const CNKH_DELETE_FAIL = "CNKH_DELETE_FAIL";

export const CNKH_RESET = "CNKH_RESET";

// CONG NO NHA CUNG CAP
export const CNNCC_LIST_LOAD = "CNNCC_LIST_LOAD";
export const CNNCC_LIST_LOAD_SUCCESS = "CNNCC_LIST_LOAD_SUCCESS";
export const CNNCC_LIST_LOAD_FAIL = "CNNCC_LIST_LOAD_FAIL";

export const CNNCC_ONE_LOAD = "CNNCC_ONE_LOAD";
export const CNNCC_ONE_LOAD_SUCCESS = "CNNCC_ONE_LOAD_SUCCESS";
export const CNNCC_ONE_LOAD_FAIL = "CNNCC_ONE_LOAD_FAIL";

export const CNNCC_POST = "CNNCC_POST";
export const CNNCC_POST_SUCCESS = "CNNCC_POST_SUCCESS";
export const CNNCC_POST_FAIL = "CNNCC_POST_FAIL";

export const CNNCC_PUT = "CNNCC_PUT";
export const CNNCC_PUT_SUCCESS = "CNNCC_PUT_SUCCESS";
export const CNNCC_PUT_FAIL = "CNNCC_PUT_FAIL";

export const CNNCC_DELETE = "CNNCC_DELETE";
export const CNNCC_DELETE_SUCCESS = "CNNCC_DELETE_SUCCESS";
export const CNNCC_DELETE_FAIL = "CNNCC_DELETE_FAIL";

export const CNNCC_RESET = "CNNCC_RESET";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

// GIAO DICH
export const GD_LISTKH = "GD_LISTKH";
export const GD_LISTKH_SUCCESS = "GD_LISTKH_SUCCESS";
export const GD_LISTKH_FAIL = "GD_LISTKH_FAIL";

export const GD_LISTNCC = "GD_LISTNCC";
export const GD_LISTNCC_SUCCESS = "GD_LISTNCC_SUCCESS";
export const GD_LISTNCC_FAIL = "GD_LISTNCC_FAIL";

export const GD_LISTLV = "GD_LISTLV";
export const GD_LISTLV_SUCCESS = "GD_LISTLV_SUCCESS";
export const GD_LISTLV_FAIL = "GD_LISTLV_FAIL";

export const GD_LISTK = "GD_LISTK";
export const GD_LISTK_SUCCESS = "GD_LISTK_SUCCESS";
export const GD_LISTK_FAIL = "GD_LISTK_FAIL";

export const GD_LISTPDH = "GD_LISTPDH";
export const GD_LISTPDH_SUCCESS = "GD_LISTPDH_SUCCESS";
export const GD_LISTPDH_FAIL = "GD_LISTPDH_FAIL";

export const GD_LISTPMH = "GD_LISTPMH";
export const GD_LISTPMH_SUCCESS = "GD_LISTPMH_SUCCESS";
export const GD_LISTPMH_FAIL = "GD_LISTPMH_FAIL";

export const GD_DEL_CTDH = "GD_DEL_CTDH";
export const GD_DEL_CTDH_SUCCESS = "GD_DEL_CTDH_SUCCESS";
export const GD_DEL_CTDH_FAIL = "GD_DEL_CTDH_FAIL";

export const GD_DEL_CTK = "GD_DEL_CTK";
export const GD_DEL_CTK_SUCCESS = "GD_DEL_CTK_SUCCESS";
export const GD_DEL_CTK_FAIL = "GD_DEL_CTK_FAIL";

export const GD_DEL_CTTT = "GD_DEL_CTTT";
export const GD_DEL_CTTT_SUCCESS = "GD_DEL_CTTT_SUCCESS";
export const GD_DEL_CTTT_FAIL = "GD_DEL_CTTT_FAIL";
